language: android
sudo: required
android:
  components:
  - tools
  - build-tools-23.0.1
  - android-23
  - extra
script: ./gradlew clean assemble test uploadArchives
before_install:
- openssl aes-256-cbc -K $encrypted_449a5e51ce83_key -iv $encrypted_449a5e51ce83_iv
  -in gradle.properties.enc -out gradle.properties -d
